# docker-compose --version
# docker-compose up
# docker-compose up -d
# docker-compose -f docker-compose-my.yml up
# docker-compose down
# docker-compose restart
# docker-compose ps

services:
  backend_web:
    container_name: spring_react
    image: spring_react
    restart: unless-stopped #on-failure
    build: ./
    ports:
      - "5555:4444"
    networks:
      - springredis

  redis:  # Redis servisi
    image: redis:latest  # Redis'in en son sürümü kullanılacak
    container_name: redis_container  # Redis konteyner ismi
    ports:
      - "6379:6379"  # Redis varsayılan portu yönlendiriliyor
    volumes:
      - redis_data:/data  # Redis verilerinin kalıcı hale gelmesi için volume kullanılıyor
    restart: unless-stopped  # Konteyner durursa otomatik başlatılır
    networks:
      - springredis

volumes:
  redis_data:  # Redis verilerini kalıcı hale getirecek volume tanımı

networks:
  springredis:
    name: springredis
    driver: bridge